### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Nhat Nam",
  "email": "nam125q@gmail.com",
  "phone": "0335495852",
  "username": "Noerean",
  "dateOfBirth": "18/03/2001",
  "address": "737/5 Lac Long Quan, Ward Bay Hien, HCM City",
  "password": "Nghia6063@",
  "registeredDate": "09/08/2025"
}

